spring:
  profiles:
#    active: local_server
    active: local
    group:
      local: local_server, common, secret
      blue: blue_server, common, secret
      green: green-server, common, secret

---

spring:
  config:
    activate:
      on-profile: local_server
server:
  port: 8080
client:
  address: http://localhost:3000

---

spring:
  config:
    activate:
      on-profile: blue_server
server:
  port: 8080
client:
  address: http://localhost:3000

---

spring:
  config:
    activate:
      on-profile: server
server:
  port: 9090
client:
  address: http://localhost:3000

---

spring:
  config:
    activate:
      on-profile: common
mybatis:
  mapper-locations:
    - mappers/*.xml